name: webproj
channels:
  - conda-forge
dependencies:
  - python >= 3.14
  - pip
  - fastapi
  - httpx2
  - proj=9.8.1
  - pyproj=3.7.2
  - pydantic
  - uvicorn
  - setuptools >= 64
  - black
  - pytest
