name: Tests
on: [push, pull_request]
jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: docker build --tag webproj .
      - run: 'docker run -d -p 80:8080 --name restapi webproj'
      - run: docker ps

      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir \
            'pyproj==3.7.2' \
            fastapi \
            'uvicorn[standard]' \
            pydantic \
            httpx \
            pytest

      - name: Sync PROJ data
        run: |
          pyproj sync --source-id dk_sdfe
          pyproj sync --source-id dk_sdfi
          pyproj sync --source-id dk_kds

      - name: Install webproj
        run: pip install .

      - name: Pytest
        run: pytest

      - run: curl -s localhost/v1.0/trans/EPSG:4258/DK:S34S/55.0,12.0 > S34S.out

      - run: echo >> S34S.out # Add's a \n at the end of the file. This satifies the diff further down.
      - run: cat S34S.out
      - run: diff test_s34s.out S34S.out
